variables:
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

image: manuel0207/energiequiz-gitlab-ci:v6 # Ensure you update the image version to reflect the changes

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - build
  - site

build-job:
  stage: build
  script:
    - export DISPLAY=:99
    - Xvfb :99 -screen 0 1024x768x16 &
    - sleep 3 # Wait a few seconds for Xvfb to start
    - mvn clean package
    - mvn checkstyle:check
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/*.zip
      - target/surefire-reports/*.xml
