= Systemidee
Als Grundlage Ihrer Entwurfstätigkeiten sollten Sie eine Vorstellung wichtiger Systemeigenschaften und Anforderungen besitzen und mindestens folgende Fragen über das System beantwortet haben.

Umfang dieses Dokuments 1-3 A4 Seiten.

== Kernaufgabe des Systems
****
NOTE: Beschreiben Sie die Kernaufgabe und Verantwortlichkeit des Systems in zwei bis drei Sätzen. Formulieren Sie positiv und benutzen Sie die Kernbegriffe der Fachdomäne.

Das System wird eine Applikation welche spielerisch durch Quiz-Fragen, Jugendlichen ein Gefühl für den Energieverbrauch im Haushalt bringen soll. 

Dabei sollen die Spieler gegeneinander, sowie alleine, spielen können.

Im Spiel starten beide im gleichen Raum des Hauses. Dort sind verschiedene Haushaltsgeräte, welche an sind. Die Spieler müssen zu diesen Geräten gehen und können dort eine Frage zum Energieverbrauch im Haushalt beantworten. Wenn sie diese Frage richtig beantworten, dann wird ihr Energieverbrauch gesenkt. Wenn der Spieler die Frage aber falsch beantwortet, kann der andere Spieler versuchen die Frage richtig zu beantworten um seinen eigenen Energieverbrauch zu senken.
Währenddem die Spieler durch das Haus laufen, können sie einander sehen, wenn sie im gleichen Raum stehen.

Dieses Konzept wird durch mehrere Räume durchgeführt und am Ende wird verglichen wie hoch die Energieverbrauche von den Spielern sind. Der Spieler mit dem niedrigsten Energieverbrauch gewinnt. Der Energieverbrauch wird während dem Spiel zum einen auf dem Bildschirm als Leiste angezeigt, als auch an der physischen Maschine als LED-Leiste.

Das ganze System basiert auf einer Java Applikation, welche auf einem vorgegebenem Raspberry Pi funktioniert. 
Die Quizfragen sollen dabei einfach, beliebig erweitert werden können.

NOTE: Fügen Sie die wichtigsten Begriffe oder Aspekte der Fachdomäne hinzu; wenige Begriffe (fünf bis zehn) genügen häufig.


Configurations-Datei

Java 

Raspberry Pi

Multiplayer

Energieverbauch

Escape-Room

NOTE: Stimmen Sie diese Formulierung mit Kunden und Auftraggebern ab!
Eine solche kurze Formulierung erleichtert die Kommunikation über das System. Sie definiert für alle Beteiligten das wichtigste Ziel (= das System). Gleichzeitig schafft sie einen begrifflichen Kontext, an dem sich alle Beteiligten orientieren können.
****

== Kategorie von System

****
[NOTE]
====
- Interaktive Online-Systeme: Auch als operationale Systeme bezeichnet, arbeiten diese Systeme als Teil der normalen Geschäftsprozesse in Unternehmen. In den meisten Fällen enthalten sie Operationen auf Daten (Transaktionen Änderungs-und Lösch-Operationen), die vom Ablauf her in die Benutzeroberfläche eingebettet sind. Die Art der Transaktionen ist festgelegt. Die Systeme operieren auf möglichst aktuellen Datenbeständen. Sie erfordern ein hohes Maß an Systemverfügbarkeit und Performance.
- Mobile Systeme: Eine (moderne) Variante von Online-Systeme - durch die starke Verbreitung von Smartphones und Tablet-Computern sehr wichtig geworden. Starker Fokus auf Benutzeroberfläche und Benutzbarkeit, oftmals per Internet an Backend-Systeme angebunden.
- Entscheidungsunterstützungssysteme (decision support system): arbeiten oftmals auf Kopien der aktuellen Unternehmensdaten (data warehouse) und enthalten hauptsächlich lesende Datenzugriffe. Die Art der Anfragen an die Daten ist flexibel. Benutzer können neue Anfragen (queries) formulieren. Daher ist die Laufzeit von Anfragen im Vorfeld kaum abschätzbar. Solche Systeme tolerieren höhere Ausfallzeiten und geringere Performance.
- Hintergrundsysteme (Offline-Systeme, Batch-Systeme): dienen hauptsächlich der Datenmanipulation, oftmals zur Vor- oder Nachverarbeitung vorhandener Datenbestände; werden zur Interaktion mit anderen Systemen eingesetzt.
- Eingebettete Systeme (embedded systems): arbeiten eng verzahnt mit spezieller Hardware. Ein Beispiel für eingebettete Systeme sind Mobiltelefone (viele haben auch Echtzeitanforderungen).
- Systeme mit Echtzeitanforderungen (real-time systems): Operationen werden innerhalb garantierter Zeiten fertiggestellt. Beispiel: Produktionssteuerung (Fließbänder mit festen Taktzeiten), Herzschrittmacher.
====

Bei dem System handelt es sich um ein System mit Echtzeitanforderungen, da der Benutzer in Echtzeit Inputs eingibt und auf diese innerhalb einer gewissen Zeit eine Antwort erwartet.

****

== Wesentliche Qualitätsanforderungen
****
[NOTE]
====
Die Qualität von Softwaresystemen wird immer bezogen auf einzelne Eigenschaften oder Merkmale. Beispiele für solche Merkmale sind Effizienz (Performance), Verfügbarkeit, Änderbarkeit, Verständlichkeit und Zuverlässigkeit.

Es gibt eine ganze Reihe unterschiedlicher Definitionen von Qualitätsmodellen und Qualitätsmerkmalen. Alle definieren einige zentrale Qualitätseigenschaften (beispielsweise Zuverlässigkeit, Effizienz, Wartbarkeit, Portabilität etc.) und verfeinern diese Eigenschaften durch eine Hierarchie weiterer Merkmale.

Egal, welches dieser Modelle Sie verwenden: Achten Sie innerhalb Ihrer Systeme oder Projekte auf eine einheitliche Terminologie für Qualitätsanforderungen. Der folgende Link zeigt Ihnen die Qualitätsmerkmale gemäss https://de.wikipedia.org/wiki/ISO/IEC_9126[DIN/ISO 9126]. Diese Norm enthält die wesentlichen Begriffe rund um Softwarequalität.

Weil unsere Systeme auch Hardware enthalten, beziehen wir die oben beschriebenen Qualitäten auf das Gesamtsystem.
====

*Stabilität:* 

Die Software soll flüssig und ohne Abstürze laufen. Zusätzlich sollte die Hardware auch genug Stabilität besitzen, dass auch nach gröberer Verwendung weiterhin alles funktioniert.


*Bedienbarkeit:* 

Die Software soll für den Benutzer leicht bedienbar sein, ohne dass dieser sich gross mit dem System auseinandersetzen muss. 
Dies ist besonders wichtig, da für die Ausstellung des Produktes eine Nutzungszeit von 1-3 Minuten gewünscht wird.


*Modifizierbarkeit:* 

Die Quizfragen und jegliche anderen Texte in der Software müssen leicht vom Kunden anpassbar sein, da sie die Sprache des Spiels anpassen wollen und eventuell auch weitere Fragen hinzufügen wollen.


*Funktionalität:* 

Die Software muss wiederholt funktionieren ohne grössere Fehler zu verursachen.
Die definierten Funktionalitäten müssen in der Endversion des Systems vorhanden sein. 


*Nachhaltigkeit?:* 

Die verwendete Hardware des Systems soll so nachhaltig wie möglich sein, ohne die Funktionalität und die Qualität des Systems zu beeinträchtigen.

****

== Relevante Stakeholder
****

NOTE: Welche Rollen oder Personen (= Stakeholder) innerhalb oder ausserhalt der Organisation haben ein Interesse am System? Beispiele sind Benutzer der Kernfunktionalität („Anwender“), Administratoren und Betreiber, Benutzer mit
Sonderfunktionen.

- Andreas Vogt, FHNW - Product Owner - andreas.vogt@fhnw.ch
- Wolfgang Szabó, Primeo Energie - Endkunde - <TODO> Kontakt hinzufügen

****

== Schnittstellen zu externen Systemen
****
[NOTE]
====
Sie sollten immer eine präzise Vorstellung der (fachlichen wie technischen) Umgebung eines Systems besitzen (= Kontext), d. h. welche Nachbarsysteme mit dem System interagieren.

Führen Sie hier eine Liste dieser Systeme auf.
====

Im System existiert eine externe Schnittstelle zu einer Datei. Diese soll vom Kunden leicht angepasst werden können, um die möglichen Quizfragen anpassen zu können. Dabei sollen die Kunden diese Fragen über Maus und Tastatur direkt am Raspberry Pi eingeben können. Es soll also keine Internetverbindung, oder ähnliches Benötigen.

Je nachdem, was mit der Verbindung von 2 Displays an einem Raspberry Pi möglich ist, muss eine weitere externe Schtnittstelle erhältlich sein. Denn wenn es nur mit einem Display pro Raspberry Pi möglich ist, werden 2 davon benötigt und diese müssen dann miteinander kommunizieren zum Synchronisieren und um zum Schluss die Punktzahl zu vergleichen.

****
